# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'pipelines-dotnet-core.csproj'  # Adjust to specify which .csproj files to build, or use a solution file

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'pipelines-dotnet-core.csproj'  # Adjust to specify which .csproj files to test

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'  # Adjust as needed for publishing

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
